# Generated by Django 5.2.8 on 2025-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="content",
            new_name="body",
        ),
        migrations.AddField(
            model_name="template",
            name="category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="footer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="header",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="language",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
